name: example
description: A sample example application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  sm_logger:
    path: ../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
