name: sm_logger
description: "A Flutter logging tool that supports printing logs to the console, writing to files, printing error information, collecting crash information, etc."
version: 0.0.9
homepage: https://github.com/shay-wong/flutter_sm_logger
repository: https://github.com/shay-wong/flutter_sm_logger

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
